# PulsoVivo - Podman Compose Configuration
# Compatible with both docker-compose and podman-compose
version: '3.8'

services:
  pulso-vivo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INVENTORY_SERVICE_URL: "/api"
        API_GATEWAY_URL: "https://erwqz80g2d.execute-api.us-east-1.amazonaws.com/api"
        AZURE_AD_CLIENT_ID: "7549ac9c-9294-4bb3-98d6-752d12b13d81"
        AZURE_AD_AUTHORITY: "https://PulsoVivo.b2clogin.com/PulsoVivo.onmicrosoft.com/B2C_1_pulso_vivo_register_and_login"
        AZURE_AD_REDIRECT_URI: "http://localhost:4000"
        ENABLE_LOGGING: "true"
    ports:
      - "4000:80"
    environment:
      - INVENTORY_SERVICE_URL=/api
      - API_GATEWAY_URL=https://erwqz80g2d.execute-api.us-east-1.amazonaws.com/api
      - AZURE_AD_CLIENT_ID=7549ac9c-9294-4bb3-98d6-752d12b13d81
      - AZURE_AD_AUTHORITY=https://PulsoVivo.b2clogin.com/PulsoVivo.onmicrosoft.com/B2C_1_pulso_vivo_register_and_login
      - AZURE_AD_REDIRECT_URI=http://localhost:4000
      - ENABLE_LOGGING=true
    container_name: pulso-vivo-frontend
    restart: unless-stopped
    networks:
      - pulso-vivo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pulso-vivo-network:
    driver: bridge
    name: pulso-vivo-network

volumes:
  nginx_cache:
    driver: local